server:
  port: 9095
# DIKKAT
# Ilk basladiginiz Ana parametre sola bitisik olmalidir.
# Ana baslik ile alt basligi ayirmak icin bir TAB bosluk kullaniniz ve cok dikkatli olun
# Ayrica gireceginiz deger:(iki nokta ust uste) den sonra bosluk birakilarak yazilmalidir.
# Aksi takdirde hataya sebep verir ve fark edilmesi cok ugrastirir.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 147852369Qw.
    url: jdbc:postgresql://localhost:5432/yemeksepeti
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
